version: "3.9"
networks:
  traefik:
    name: traefik
    external: true

services:
  nginx:
    image: nginx:stable
    container_name: homepage
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`staging.hackutt.uttnetgroup.fr`)
      - traefik.http.routers.homepage.entryPoints=websecure
      - traefik.http.routers.homepage.tls=true
      - traefik.http.routers.homepage.tls.certresolver=letsencrypt
      - traefik.http.routers.homepage.service=homepage
      - traefik.http.services.homepage.loadbalancer.server.port=80
    networks:
      - traefik
